server.port: 7002

logging:
  level:
    root: INFO
    microservices.core: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
      auto-index-creation: true
  profiles:
    group:
      "docker": "docker"

---
spring:
  config:
    activate:
      on-profile: "docker"
  data:
    mongodb:
      host: mongodb
server:
  port: 8080

