server.port: 7002

logging:
  level:
    root: INFO
    microservices.core: DEBUG

spring:
  profiles:
    group:
      "docker": "docker"

---
spring:
  config:
    activate:
      on-profile: "docker"
server:
  port: 8080

