server:
  port: 7002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation
      auto-index-creation: true
  profiles:
    group:
      "docker": "docker"
      
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      definition: recommendations
    stream:
      default-binder: rabbit
      default:
        contentType: application/json
      bindings:
        recommendations-in-0:
          destination: recommendations
          group: recommendationsGroup
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    microservices.core: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    
---
server:
  port: 80
  
spring:
  config:
    activate:
      on-profile: "docker"
  data:
    mongodb:
      host: mongodb
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka