version: '2.4'

services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/review-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5Dialect
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    
    # $ mongo
  mongodb:
    image: arm64v8/mongo:4.0
#    platform: "linux/x86_64"
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    platform: "linux/x86_64"
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uuser", "-p1234", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10