server:
  port: 7001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      auto-index-creation: true
  profiles:
    group: 
      "docker": "docker"
  
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
  cloud:
    function:
      definition: products;
    stream:
      default-binder: rabbit
      default:
        contentType: application/json
      bindings:
        products-in-0:
          destination: products
          group: productsGroup
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    microservices.core: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    
---
server:
  port: 80
  
spring:
  config:
    activate:
      on-profile: "docker"
  data:
    mongodb:
      host: mongodb
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka