server:
  port: 7001

logging:
  level:
    root: INFO
    microservices.core: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true
      
  profiles:
    group: 
      "docker": "docker"
      
  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
      bindings:
        input:
          destination: products
          group: productsGroup
          consumer:
            partitioned: true
            instance-index: 0
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0

---
spring:
  data:
    mongodb:
      host: mongodb
  config:
    activate:
      on-profile: "docker"
server:
  port: 8080

