server.port: 7003

logging:
  level:
    root: INFO
    microservices.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/review-db
    username: user
    password: 1234
    hikari:
      initialization-fail-timeout: 60000
  profiles:
    group:
      "docker": "docker"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: reviews
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindlq: true
      default-binder: rabbit
      default:
        contentType: application/json
      bindings:
        reviews-in-0:
          destination: reviews
          group: reviewsGroup
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile: "docker"
  datasource:
    url: jdbc:mysql://mysql:3306/review-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

server:
  port: 8080